language: rust
rust:
  - stable
  - 1.4.0
  - beta
  - nightly
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - |
      travis-cargo build &&
      RUST_TEST_THREADS=1 travis-cargo test &&
      travis-cargo bench &&
      travis-cargo doc
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo
env:
  global:
    secure: OlWU0rTAKYV6NCHamtjs8GNYyBLd0x8xWTan482Da1zsWVIKFDEXjj2ymiTcz3SnDbTZWDnulsvQ2e/Cj8/7XogDcWmp73D3cxgHD2Glj5nZFdBHz+Gtt+bW5S0KYwnxv6UNmENcJZmRnIQDzSDVqkW6APKhJGUSJSRK4RCSk4I=
notifications:
    webhooks: http://huon.me:54856/travis
